### ISSUE TITLE
Monitoring Construct in Stack in Pipeline Stage

### ISSUE THREAD

**Issue by AlessandroVol23** [cdklabs/cdk-monitoring-constructs#146]
### Version

1.7.0

### Steps and/or minimal code example to reproduce

My issue is that the monitoring construct runs within a stage and doesn't deploy any resources.

My steps were:

1. CDK App has a stack `CdkPipeline`
2. `CdkPipeline` has a `stage` `CdkPipelineStage`
3. `CdkPipelineStage` includes all `stacks`
4. Add monitoring stack in `CdkPipelineStage`

```ts
export interface Props extends StackProps {
  constructToMonitor: ConstructType;
}
export class MonitoringStack extends Stack {
  constructor(parent: Construct, name: string, props: Props) {
    super(parent, name, props);

    const { constructToMonitor } = props;

    const monitoring = new MonitoringFacade(this, 'monFacade', {
      alarmFactoryDefaults: {
        actionsEnabled: true,
        alarmNamePrefix: 'alarm'
      },
      metricFactoryDefaults: {}
    });

    monitoring.monitorScope(constructToMonitor);
    monitoring.monitorBilling();
    monitoring.monitorLambdaFunction({
      lambdaFunction: constructToMonitor.sqsLambdaDlq.consumerLambda
    });
  }
}
```

5. Nothing gets deployed except for CDK Metadata

The same thing happens if I am adding the monitoring construct within an existent stack with other services.

Is it necessary that I pass the `App` like in the example or is it also possible when I pass a construct? 

### Expected behavior

Find all resources within my construct and create alarms, dashboards, etc.

### Actual behavior

Nothing will be deployed.

**Comment by AlessandroVol23** [comment]
Thanks the quick reply.

1. I just renamed it. The `ConstructType` is a class that extends the type `Construct` 

This is the definition of the class
```
export class ArticleCircleService extends Construct {}
```

2. Resource and Constructs within that construct
- SQS Queue
- SQS DLQ
- Lambda
- Lambda for DLQ
- Log groups for lambda

3. Snippet of `CdkPipelineStage`

```ts
export class CdkPipelineStage extends Stage {
  constructor(
    scope: Construct,
    id: string,
    pipelineEnv: PipelineEnvironment
  ) {
    super(scope, id, pipelineEnv);

    const microservices = new MicroservicesStack(this, 'Services', {...});

    new MonitoringStack(this, 'MonitoringStack', {
      articleCircleService: microservices.articleService
    });
  }
}
```

I hope that helps! :)

**Comment by wernermorgenstern** [comment]
I am having the same issue.

**Comment by echeung-amzn** [comment]
@AlessandroVol23 @wernermorgenstern Are either of you able to provide a minimum repro project? If not, can you provide some more info including your dependency versions and basic descriptions of your setup so we can try to repro?

**Comment by wernermorgenstern** [comment]
I will see if I can create a simple quick setup project.


From: Eugene Cheung ***@***.***>
Date: Friday, May 27, 2022 at 10:08
To: cdklabs/cdk-monitoring-constructs ***@***.***>
Cc: Werner Morgenstern ***@***.***>, Mention ***@***.***>
Subject: Re: [cdklabs/cdk-monitoring-constructs] Monitoring Construct in Stack in Pipeline Stage (Issue #146)

@AlessandroVol23<https://github.com/AlessandroVol23> @wernermorgenstern<https://github.com/wernermorgenstern> Are either of you able to provide a minimum repro project? If not, can you provide some more info including your dependency versions and basic descriptions of your setup so we can try to repro?

**Comment by wernermorgenstern** [comment]
@echeung-amzn , I am using CDK V 2.25. Is that an issue with that?

**Comment by echeung-amzn** [comment]
Seems to work fine in a test app (cf. [commit](https://github.com/echeung-amzn/sample-cdk-monitoring-app/commit/5349bcf257ce4ccef8151894cb921d3689539c11)).

Are your sure your CDK app has the stack instantiated (like [this example](https://github.com/echeung-amzn/sample-cdk-monitoring-app/blob/5349bcf257ce4ccef8151894cb921d3689539c11/bin/sample-cdk-monitoring-app.ts#L7))?

**Comment by wernermorgenstern** [comment]
@echeung-amzn , I use Pipelines, with a Stage, which contains the Stack.  
Should be Monitoring be a nested Stack, for each one of the Stacks?

**Comment by echeung-amzn** [comment]
I wouldn't expect the usage of a `CodePipeline` to affect it. Were you able to create a minimum repro project?

**Comment by wernermorgenstern** [comment]
Ok, I will create a quick minimum repro project.

**Comment by wernermorgenstern** [comment]
@echeung-amzn , sorry for the late response.  Due to the Holiday Weekend, I wasn't able to get to it till today.  I am using your Sample Repo, and just deploying it as it is to my AWS Account. [https://github.com/echeung-amzn/sample-cdk-monitoring-app](url). However, when I go to the Cloudwatch Dashboard, no Dashboard is created.  So still the same issue.

**Comment by echeung-amzn** [comment]
@wernermorgenstern What ended up being the difference between what you had before and after?

**Comment by echeung-amzn** [comment]
Thanks, we'll take an action item to improve the documentation. A recent release ([v1.8.0](https://github.com/cdklabs/cdk-monitoring-constructs/releases/tag/v1.8.0)) actually introduced a more sensible default if it isn't explicitly declared.

@AlessandroVol23 Can you verify whether this is relevant to what you're seeing?

**Comment by wernermorgenstern** [comment]
@echeung-amzn , I am using 1.8.1, and when I do a synth, I get a warning like this:

[Warning at /PIPELINE_STACK/nAP:P_STAGE/STACK_NAME/notifications-Dashboard-AppSync/SummaryDashboard] Math expression 'SEARCH('{AWS/EC2,InstanceId}  MetricName="DiskReadOps"', 'Average', 300)' references unknown identifiers: nstanceId, etricName, iskReadOps, verage. Please add them to the 'usingMetrics' map.

Even though I don't have a EC2 instance stack.
I am using for now monitorScope, to see what is available to monitor, and have alarms.

**Comment by wernermorgenstern** [comment]
@echeung-amzn , thank you.

I also have a small issue, and not sure how to resolve this.  I am creating a Dashboard for AppSync.  So I added the GraphQL API to monitor, and then 8 Lambda Functions (which are used for the resolvers).  For right now, I enabled all the alarms for the GraphQL and the Lambda Functions.  And I am not able to deploy the Stack, as it is bigger than 1,000,000 bytes.
I was able to get it deployed, by removing the Warning Alarms, and just enable the Critical Alarms.
Is there something I am doing wrong?

**Comment by ayush987goyal** [comment]
That is a known limitation of CloudFormation and monitoring resources since there can be many such alarms for all of your resources.

To get around to this, you can consider using a `NestedStack` inside you main stack that contain your AppSync API and Lambdas. You can then place the monitoring related resources (facade, monitoring, alarms etc.) in this `NestedStack` and pass down the references for the API/Lambdas to this stack as props. This way both the stacks will have their own size/resource limits.

**Comment by wernermorgenstern** [comment]
I was able to deploy it now.  I put a question in under the discussions for a small improvement which could be done.

**Comment by JannikWempe** [comment]
> I was able to deploy it now. I put a question in under the discussions for a small improvement which could be done.

@wernermorgenstern could explain how you integrated `cdk-monitoring-constructs` with CDK pipelines?
