### ISSUE TITLE
monitorGlueJob creates metric with scale 0-100, but value is scale 0-1

### ISSUE THREAD

**Issue by jkldv** [cdklabs/cdk-monitoring-constructs#159]
The leftYAxis is specified as a percentage from 0 to 100, but the source glue cpuUsageMetric and heapMemoryUsageMetrics are 0 to 1 values.
https://github.com/cdklabs/cdk-monitoring-constructs/blob/b66685e82733c966eba1555de42c174e1de78a59/lib/monitoring/aws-glue/GlueJobMonitoring.ts#L220
Here is where the metric is built it comes from "glue.ALL.system.cpuSystemLoad" which ranges from 0 to 1. (Similar for heap usage metric as well)
[https://github.com/cdklabs/cdk-monitoring-constructs/blob/b66685e82733c966eba1555d[…]42c174e1de78a59/lib/monitoring/aws-glue/GlueJobMetricFactory.ts](https://github.com/cdklabs/cdk-monitoring-constructs/blob/b66685e82733c966eba1555de42c174e1de78a59/lib/monitoring/aws-glue/GlueJobMetricFactory.ts#L57)
AWS Glue Metrics, state scale is 0-1
https://docs.aws.amazon.com/glue/latest/dg/monitoring-awsglue-with-cloudwatch-metrics.html
I think we either need to use a math metric to multiply the glue metric values by 100 or change the range to 0 to 1 and label it something other than "%".

**Comment by voho** [comment]
Thanks for your submission, this is definitely a bug we will fix.

**Comment by voho** [comment]
Indeed, the unit is wrong, fixing it now.

https://docs.aws.amazon.com/glue/latest/dg/monitoring-awsglue-with-cloudwatch-metrics.html
