### ISSUE TITLE
Monitoring support for AWS DocumentDB

### ISSUE THREAD

**Issue by chalu** [cdklabs/cdk-monitoring-constructs#167]
### Feature scope

DocumentDB

### Describe your suggested feature

I just installed v1.10.0 and it does appear that there isn't support for monitoring AWS DocumentDB via this library? I am kindly requesting that this be considered and added, if it's not already been planned.

**Comment by voho** [comment]
Thank you, sounds like a great idea! Is there any particular metric/alarm you would like to see first?

**Comment by voho** [comment]
https://docs.aws.amazon.com/documentdb/latest/developerguide/cloud_watch.html

**Comment by voho** [comment]
Hi @chalu, what alarms would you like to have? You can pick from the aforementioned metrics (we can add more later, but in another PR).

**Comment by voho** [comment]
Hi, this is a very long list - do you really want to have all of these metrics for each cluster? We will start with a subset, allowing you to add custom ones as needed (to fill the gaps), so you do not need to wait for such a long time.

**Comment by charlessensibill** [comment]
Yeah,. I wanted to list some of the metrics we are prioritising. Was definitely not expecting all of them to be implemented in this issue ticket. 
For the sake of this ticket, I've cut the list down to a more reasonable number. 
I am happy to contribute other metrics/alarms after the initial DocDB support is in place.

Thanks
