### ISSUE TITLE
[dynamo] Disallow utilization metrics/alarms if a table is using on-demand capacity

### ISSUE THREAD

**Issue by echeung-amzn** [cdklabs/cdk-monitoring-constructs#185]
### Version

v1.14.0

### Steps and/or minimal code example to reproduce

1. Monitor a DDB table
2. Note that the Utilization metrics in the dashboards show warnings
3. Note that you can technically create alarms against utilization metrics

### Expected behavior

If a DDB table is using on-demand capacity, the utilization metrics should be excluded from the dashboard widgets and alarms should not be able to be created.

### Actual behavior

Dashboards include metrics and you can create (invalid) alarms.

**Comment by echeung-amzn** [comment]
Dashboarding portion was addressed by #186.

**Comment by voho** [comment]
Thanks for creating this. What would you propose as an ideal solution? I could imagine even having two separate types and implementations. If the table type decision is done on compile-time, we would have to have two monitoring functions (e.g. `monitorOnDemandDynamoTable()` and `monitorProvisionedDynamoTable`) and third legacy one (`monitorDynamoTable`) with autodetection, which would allow users to do anything they want, even though it does not make sense for the given table type.

**Comment by echeung-amzn** [comment]
Having separate functions would offer as much compile-time safety as the existing one ("legacy" in that scenario) since it'd still rely on either being able to programmatically detect it or having the `billingMode` be explicitly declared as a prop.

We could piggyback on the work you did in #186 to use the `billingMode` to control the validity of the utilization alarms (i.e., throw errors when it's `PAY_PER_REQUEST`)?

**Comment by echeung-amzn** [comment]
I believe we're actually good to close this, I don't think any of the alarmable metrics rely on provisioned capacity metrics.
