### ISSUE TITLE
Introduce OpsItemActionStrategy for creating ops items in ops center

### ISSUE THREAD

**Issue by stocks29** [cdklabs/cdk-monitoring-constructs#187]
### Feature scope

N/A

### Describe your suggested feature

It would be great to have a `OpsItemActionStrategy` which creates ops items in ops center with a default category and severity which could be overridden for each alarm.

**Comment by voho** [comment]
Great idea, please checkout the PR :).

**Comment by stocks29** [comment]
@voho , PR looks great, thanks!
