### ISSUE TITLE
Allows users specify minimal sample size below which the alarm will be suppressed and considered unreliable

### ISSUE THREAD

**Issue by KoStard** [cdklabs/cdk-monitoring-constructs#198]
### Feature scope

Alarming

### Describe your suggested feature

The need for this feature is most visible when alarming on the AVERAGE, P90, P99... of some metric, which might contain sparse datapoints and hence decrease the reliability of the aggregated value.

Example:
You have an alarm on the P99 Latency metric. But during nights the TPS is going very low, hence you don't get enough records to reliably understand if there is an issue increasing latency or it's because of regular cache misses, retries, etc... If during 1 minute you got only a few calls to the service, the P99 latency won't be reliable reprepsentation of the health of the system. Hence we don't want to alarm on it.

With the current setup of the monitoring constructs, this is not easily possible. We have to create the composite alarms manually, add the actions, deal with the sample size metrics, etc...

By adding this to the library, we'll allow users to create alarms that are closer to their needs.

Definition of done:
- By adding a field to the alarms definition, the users can define minimal sample size after which they want the alarm to be enabled
- The change should be backwards compatible

**Comment by voho** [comment]
We were talking about adding a parameter to addAlarm properties, e.g. `addMinSampleCountCondition: number`; in order to enable more conditions in the future, we might also consider adding something like `addAlarmConditions: {minSampleCount: X}}`, allowing us to add e.g. composing with other alarms and so on
