### ISSUE TITLE
[fargate] Support FargateService in MonitoringFacade.monitorFargateService

### ISSUE THREAD

**Issue by bjoc1** [cdklabs/cdk-monitoring-constructs#224]
### Feature scope

MonitoringFacade.monitorFargateService

### Describe your suggested feature

Currently monitoring using `MonitoringFacade.monitorFargateService` API only supported on the following Fargate constructs: `NetworkLoadBalancedFargateService`, `ApplicationLoadBalancedFargateService`.
Can you please add support to `FargateService` type as well.

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs.FargateService.html

Thank you.

**Comment by openwebsolns** [comment]
+1 on request. One work-around available today seems to be:

```js
import * as monitoring from "cdk-monitoring-constructs";

// monitor = new monitoring.MonitoringFacade(...);
// fargateService = cdk.FargateService instance

monitor.addSegment(
  new monitoring.FargateServiceMonitoring(monitor, { fargateService })
);
```

In other words, `FargateServiceMonitoring` supports a [raw FargateService instance](https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-ecs-patterns/FargateServiceMonitoring.ts#L135) while the method on MonitoringFacade [does not](https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/facade/MonitoringFacade.ts#L445). Thus, I think the fix here is to swap `FargateServiceMonitoringProps` for `CustomFargateServiceMonitoringProps`.

**Comment by r0b0ji** [comment]
Doesn't `facade.monitorSimpleFargateService({ fargateService })` work?

https://github.com/cdklabs/cdk-monitoring-constructs/blob/edfc4e4bcb68f7f71df18fc2acab84f130ce3988/lib/facade/MonitoringFacade.ts#L456-L463

**Comment by echeung-amzn** [comment]
`facade.monitorSimpleFargateService({ fargateService })` should indeed fulfill this need, but let me know if I'm missing something.
