### ISSUE TITLE
[rds] Connection monitor should use AVERAGE not SUM

### ISSUE THREAD

**Issue by relm923** [cdklabs/cdk-monitoring-constructs#231]
### Version

1.22.0

### Steps and/or minimal code example to reproduce

```typescript
new MonitoringFacade(this, 'Monitoring', {}).monitorRdsCluster({ cluster });
```

### Expected behavior

Connection count monitor should be an average (not sum) for readability and to match the default RDS monitor dashboard

### Actual behavior

Its using SUM which leads to a confusing over count of connections

**Comment by relm923** [comment]
Happy to open a PR as well

**Comment by echeung-amzn** [comment]
Since this is used for the dashboard and not alarming, this seems safe to do as a regular bug fix. A PR would be welcomed!
