### ISSUE TITLE
[rds] Add ability to alarm on DB connections

### ISSUE THREAD

**Issue by relm923** [cdklabs/cdk-monitoring-constructs#232]
### Feature scope

RDS

### Describe your suggested feature

Add ability to configure alarm on Cluster connections similar to `addCpuUsageAlarm`

**Comment by echeung-amzn** [comment]
Related: #231

**Comment by relm923** [comment]
Happy to make a PR here but will likely need a bit of guidance

**Comment by echeung-amzn** [comment]
In general you can follow the same pattern as existing alarms.

1. Add a new prop: https://github.com/cdklabs/cdk-monitoring-constructs/blob/e1fbff5ba0b075d85640a3a04c9d89c41ede5fc2/lib/monitoring/aws-rds/RdsClusterMonitoring.ts#L32
2. Create an alarm based on the props using the relevant metric (which happens to already exist in this case): https://github.com/cdklabs/cdk-monitoring-constructs/blob/e1fbff5ba0b075d85640a3a04c9d89c41ede5fc2/lib/monitoring/aws-rds/RdsClusterMonitoring.ts#L88
3. Add some unit tests: https://github.com/cdklabs/cdk-monitoring-constructs/blob/e1fbff5ba0b075d85640a3a04c9d89c41ede5fc2/test/monitoring/aws-rds/RdsClusterMonitoring.test.ts
4. Document any new functionality in the table in the README
