### ISSUE TITLE
[rds] Add Monitoring for RDS DB Instance

### ISSUE THREAD

**Issue by kinano** [cdklabs/cdk-monitoring-constructs#236]
### Feature scope

RDS

### Describe your suggested feature

The library currently supports out-of-the-box monitoring for RDS Clusters using [monitorRdsCluster](https://github.com/cdklabs/cdk-monitoring-constructs/blob/a371e31593fa3ef96a7dd74a47937f2cf2537395/lib/facade/MonitoringFacade.ts#L589-L593)

Would it be possible to add support to monitor [RDS DB Instances](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseInstance.html)? We currently have to roll our own widgets to be able to do this.

**Comment by voho** [comment]
Could you share the widgets you created? You probably have some idea on what you expect to get. Thanks!

**Comment by kinano** [comment]
> Could you share the widgets you created? You probably have some idea on what you expect to get. Thanks!

Absolutely, I ended up wiring up a [hand-crafted dashboard](https://gist.github.com/kinano/c8fc0b4e645bdf4be99c0aa9968e3375) that includes: 
- a link to the RDS Performance insights for the instance (it is always a pain to find things in rds UI on the console)
- a bunch of widgets & alarms for:
  - CPU Utilization
  - Latencies
  - Connections
  - Storage
  - Throughput (read/write/network)

**Comment by lucasgadams** [comment]
Any update on this?
