### ISSUE TITLE
[redshift] Alarm for number of connections to Redshift cluster

### ISSUE THREAD

**Issue by MicahHarrison** [cdklabs/cdk-monitoring-constructs#248]
### Feature scope

AWS/Redshift

### Describe your suggested feature

Alarm for maximum number of connections allowed to redshift cluster for connections widget created by .monitorRedshiftCluster. https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-redshift/RedshiftClusterMonitoring.ts#L81

**Comment by voho** [comment]
https://github.com/cdklabs/cdk-monitoring-constructs/pull/251
