### ISSUE TITLE
[redshift] Alarm on long query duration

### ISSUE THREAD

**Issue by MicahHarrison** [cdklabs/cdk-monitoring-constructs#249]
### Feature scope

AWS/Redshift

### Describe your suggested feature

Allow for alarm on long query duration. https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-redshift/RedshiftClusterMonitoring.ts#L90

**Comment by voho** [comment]
https://github.com/cdklabs/cdk-monitoring-constructs/pull/251
