### ISSUE TITLE
Enable descriptions on dashboards

### ISSUE THREAD

**Issue by rajivsarvepalli** [cdklabs/cdk-monitoring-constructs#256]
### Feature scope

Dashboards

#### Feature overview
Users should have the ability to add some kind of captions or descriptions to dashboards if they want.

#### Background
Sometimes it is important for service owners to provide dashboards that have sufficient context in dashboard text, for example with description text beside or below each graph.

For example, something like:
![](https://d1.awsstatic.com/builderslibrary/architecture-images/building-dashboards-for-operational-visibility-6.0c036582ffe6990d2f461638eb6e44eba3755c07.png)

In general, the guide [Building dashboards for operational visibility](https://aws.amazon.com/builders-library/building-dashboards-for-operational-visibility/) provides some good principles for designing dashboards. This feature would help align with the design principle:
> We don't assume the user knows exactly what every metric or widget means

**Comment by voho** [comment]
I agree with the idea and I definitely second that it is important to explain what different things mean, that is why we have the description feature in custom metrics. Doing it for all monitors sounds like a good idea. Will think about an API. Most probably, we will add some markdown text with a custom height, which will be placed below the title.

**Comment by echeung-amzn** [comment]
#276 addresses this for headers.

Were you hoping to be able to reuse something like `HeaderWidget` for other use cases like that screenshot (i.e. not a full width widget)?
