### ISSUE TITLE
Stack deployment fails due to error that dashboard already exists

### ISSUE THREAD

**Issue by oceanofmaya** [cdklabs/cdk-monitoring-constructs#357]
### Version

3.1.2

### Steps and/or minimal code example to reproduce

When `MonitoringFacade` is created with `dashboardFactory` as `undefined`, it uses whatever was passed as the id as the `dashboardNamePrefix`. Refer https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/facade/MonitoringFacade.ts#L169 and a default dashboard is created with the `dashboardNamePrefix` as the physical id/name.

In my case I pass the stack name as the id when creating the `MonitoringFacade` and create alarms using `monitorScope` and it generates the default dashboard. I later updated my code to remove an alarm e.g. lambda latency alarm for p50 and deployed the stack. Here the CDK diff indicated that the dashboard would need to be destroyed and a new one with a different logical id created. Since CFT creates the new resource first before replacing/destroying existing resource, the stack deployment fails since the dashboard name is the physical id of the dashboard and it errors out stating Dashboard 'name' already exists.

### Expected behavior

Dashboard physical id (name of the dashboard) when defaults are used has an md5 hash to allow replacements.

Perhaps it could be the md5 hash that is in the logical id of the dashboard or something else, which would allow for a replacement to occur without needing to either delete the dashboard and creating again or creating a dashboard with a new name by supplying an override for the `dashboardNamePrefix`.

### Actual behavior

Replacement of dashboard fails as the dashboard name already exists.

### Other details

Please let me know if passing something else as the id for the MonitoringFacade be a better idea.

**Comment by echeung-amzn** [comment]
I'm not sure I follow the reproduction steps, dashboard resources are typically just updated, not fully replaced.

Do you have specific example commits that'd demonstrate the behaviour?

**Comment by oceanofmaya** [comment]
I removed the alarm in red from LambdaFunctionMonitoringOptions that was passed along to the monitorScope
![image](https://user-images.githubusercontent.com/33257049/231877275-a873d830-2614-44c8-aefe-708a772f9790.png)

Here is a CDK diff on that
![image](https://user-images.githubusercontent.com/33257049/231879180-1589cc51-12a8-45f8-a7bc-bcb5a64e9c98.png)

Note: I had other updates the resulted in Gateway replacement as well.

The deployment failed as it tried to create the new dashboard first before destroying the old one as it determined it needed to be replaced
![image](https://user-images.githubusercontent.com/33257049/231880130-4b8f416e-bc56-4f52-8138-e28f96cbe20e.png)

**Comment by alexhafner** [comment]
I had run into the same issue when upgrading a Python-based CDK stack that was previously on Release 2.5.3. All releases from  3.0.5 upwards to 4.0.3 fail with the error reported here, I have pinned `cdk-monitoring-constructs==3.0.4` as a workaround

**Comment by dominiquearpin** [comment]
I got the same error when upgrading from 3.0.2 to 4.0.3 (typescript based cdk)
