### ISSUE TITLE
Alarms created for ApiGateway using monitorScope uses the default stage "prod" instead of the stage deployed

### ISSUE THREAD

**Issue by oceanofmaya** [cdklabs/cdk-monitoring-constructs#381]
### Version

v4.0.9

### Steps and/or minimal code example to reproduce

Since the stacks created at my organizations are deployed to multiple environments (development, staging, production etc) and depending on the environment it exists in the stage in the ApiGateway is different. When I use `monitorScope` for `apiGateway` it is creating alarms for the stage `prod` (which appears to be the default when `apiStage` is not provided) instead of what I have in the ApiGateway that is deployed. I'm not seeing a way to specify `apiStage` when using `monitorScope`. Shouldn't that automatically deduce that when it uses Aspects or is there a way to specify it when using `monitorScope` that I missed?

Below is an example code that I use:

```
 monitoringFacade.monitorScope(this, {
        apiGateway: {
          props: {
              add5XXFaultRateAlarm: {
                Warning: {
                  maxErrorRate: 0.1,
                  datapointsToAlarm: 2,
                  treatMissingDataOverride: TreatMissingData.NOT_BREACHING,
                },
              },
              add4XXErrorRateAlarm: {
                Warning: {
                  maxErrorRate: 0.2,
                  datapointsToAlarm: 2,
                  treatMissingDataOverride: TreatMissingData.NOT_BREACHING,
                },
              },
          },
          enabled:  true,
        }
     }
   );
```

### Expected behavior

The alarms that are created for ApiGateway when using `monitorScope` uses the stage that exists in ApiGateway based on the template. Alternatively, provide a way to override the default if there are challenges to made this deduction using aspects.

### Actual behavior

The alarms are created for stage `prod`

**Comment by oceanofmaya** [comment]
Here it does not add the `apiStage` using the `deploymentStage` information from the apiGateWay https://github.com/cdklabs/cdk-monitoring-constructs/blob/fbd348c4eaa2e406c86727359d88d1c70ae72d80/lib/facade/MonitoringAspect.ts#L108

And since it is not added the default `prod` from https://github.com/cdklabs/cdk-monitoring-constructs/blob/fbd348c4eaa2e406c86727359d88d1c70ae72d80/lib/monitoring/aws-apigateway/ApiGatewayMonitoring.ts#L114 gets used.

The code I'm pointing to above is 5.x of the cdk-monitoring constructs, but 4.x is probably similar. This results in the alarms created for the wrong deployment stage in my case when I use `monitorScope`.

**Comment by corey-cole** [comment]
This might need to be re-opened.  Following the notes here, I'm monitoring an APIGW and neither the dashboard title nor CW metrics reflect the configured stage name:

```python
        restapi = apigateway.RestApi.from_rest_api_id(self, "RestApi",
            "nqfaopfeuk"
        )
        monitoring.monitor_api_gateway(api=restapi, api_stage='latest')
```

CloudWatch dashboard source (snippet)
```json
"metrics": [
                    [ "AWS/ApiGateway", "Latency", "ApiName", "RestApi", "Stage", "prod", { "label": "P50 (avg: ${AVG})", "stat": "p50" } ],
                    [ "AWS/ApiGateway", "Latency", "ApiName", "RestApi", "Stage", "prod", { "label": "P90 (avg: ${AVG})", "stat": "p90" } ],
                    [ "AWS/ApiGateway", "Latency", "ApiName", "RestApi", "Stage", "prod", { "label": "P99 (avg: ${AVG})", "stat": "p99" } ]
                ],
```

APIGW in question only has a single stage (latest) and definitely does not have one named 'prod'.

**Comment by oceanofmaya** [comment]
@corey-cole The bug fix applied here was done for the `monitorScope` method where it was not passing the ApiGateway deployment stage when it internally invoked `monitorApiGateway` and that resulted in the default `prod` as the stage name always because there wasn't one supplied. Before the fix I was able to workaround it by directly invoking `monitorApiGateway`  and passing along the stage name. With the fix in place, I went back to using `monitorScope`.  In my use case I have stage names like development, production etc depending on where my stack is deployed and the fix works for me and the correct stage name is reflected. I'm using the Typescript version of the library.

The fix added deployment stage to `monitorScope` https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/facade/MonitoringAspect.ts#L109

In `monitorApiGateway` the default `prod` is only used if apiStage was not provided https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/monitoring/aws-apigateway/ApiGatewayMonitoring.ts#L118

In your example I see you are passing the `api_stage` but looks like it isn't being reflected. While it is unrelated to this fix as this was done to `monitorScope` and did not change the behavior of `monitorApiGateway` the code in the `monitorApiGateway` does use the apiStage when passed at least for the Typescript based library. I'm not sure why it isn't working in your case. Maybe one of the contributors can weigh in and you could consider opening a new bug.

**Comment by echeung-amzn** [comment]
I don't see a good reason why it wouldn't use your supplied `api_stage` unless there's some JSII-weirdness going on. Can you open a new issue with more details including what version you're using, and ideally a minimal project that reproduces the issue?
