### ISSUE TITLE
[lambda] MonitoringFacade Alarming Inaccuracy/Bad Method Name

### ISSUE THREAD

**Issue by andrewt370** [cdklabs/cdk-monitoring-constructs#39]
The below code generates the attached dashboard image. IteratorAge is it's own lambda metric, independent of Duration. Is there a miss in my configuration?

```
monitoring.monitorLambdaFunction({
....
                addMaxIteratorAgeAlarm: {
                    Warning: {
                        maxAgeInMillis: ...
                    },
....
```

![Screen Shot 2022-03-04 at 12 41 00 PM](https://user-images.githubusercontent.com/53320850/156838836-2bbe2140-3236-4d83-9ce1-e5efddb9db0a.png)

**Comment by voho** [comment]
Will check the code, maybe there is an error in where the annotation is put.

**Comment by voho** [comment]
After a quick peek, I do not see anything suspicious. Could you please share the whole Lambda monitoring fragment? Thanks!

**Comment by echeung-amzn** [comment]
This is a bug with an earlier version where the annotations for `addIteratorMaxAgeAlarm ` were pushed to `this.latencyAnnotations` incorrectly.

This has been since fixed, so closing this.
