### ISSUE TITLE
ECS monitoring for disk space

### ISSUE THREAD

**Issue by btd** [cdklabs/cdk-monitoring-constructs#399]
### Feature scope

ECS Fargate

### Describe your suggested feature

Hi, thank you for super useful lib.

I would like to propose to add disk space usage (fill) to the existing Fargate monitoring. 

Metrics: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html `EphemeralStorageReserved` and `EphemeralStorageUtilized` so that i can alarm when task disk almost fill.

**Comment by ryxli** [comment]
In a similar vein, adding all container insight metrics to monitorEc2Service would be very helpful
