### ISSUE TITLE
Issues while using monitorFargateApplicationLoadBalancer function to add fargate monitors

### ISSUE THREAD

**Issue by 19Sravanidulipalla18** [cdklabs/cdk-monitoring-constructs#406]
### Version

"^1.28.1"

### Steps and/or minimal code example to reproduce

We don't have access to the actual CDK resource i.e the FargateService resource that's actually getting created. We are using the cdk-monitoring-constructs provided utility monitorFargateApplicationLoadBalancer function to add fargate monitors. We are using the imported FargateService resource, but we are gettting error "Invalid type of load balancer or target group (only ALB and ELB is supported)."

### Expected behavior

We are expecting to use monitorFargateApplicationLoadBalancer function to add fargate monitors.

### Actual behavior

We don't have access to the actual CDK resource i.e the FargateService resource that's actually getting created. We are using the cdk-monitoring-constructs provided utility monitorFargateApplicationLoadBalancer function to add fargate monitors. We are using the imported FargateService resource, but we are gettting error "Invalid type of load balancer or target group (only ALB and ELB is supported)."

**Comment by echeung-amzn** [comment]
Please upgrade to v3.0.0 or higher to leverage https://github.com/cdklabs/cdk-monitoring-constructs/commit/0f97cdaa63d5240f0ac8e36bc6d4ee35fda98ed8
