### ISSUE TITLE
Cannot create an Alarm based on a MathExpression which specifies a searchAccount or searchRegion

### ISSUE THREAD

**Issue by Laxenade** [cdklabs/cdk-monitoring-constructs#428]
### Version

5.10.0

### Steps and/or minimal code example to reproduce

I have a few constructs that create DDB alarms, they used to be work with 5.4.2 but fails to build with 5.10.0, I am getting

```
Cannot create an Alarm based on a MathExpression which specifies a searchAccount or searchRegion
```

Here is my alarm config

```
addReadThrottledEventsCountAlarm: {
  Critical: {
    maxThrottledEventsThreshold: 0,
    datapointsToAlarm: 1,
    period: Duration.minutes(1),
    treatMissingDataOverride: TreatMissingData.NOT_BREACHING,
  }
}
```

### Expected behavior

DDB alarms are created.

### Actual behavior

Not able to get alarms created.

### Other details

I think this is related to #415 where we added `searchAccount` and `searchRegion` to `createMetricMath` and ReadThrottledEventsCountAlarm and WriteThrottledEventsCountAlarm use math expression.

https://github.com/cdklabs/cdk-monitoring-constructs/blob/b07f3615de87e160081834d4816a1617565a1e76/lib/monitoring/aws-dynamo/DynamoTableMetricFactory.ts#L138-L141

The change impacts more than just DDB alarms I feel, it affects all alarm creations where math expression will be used

**Comment by Laxenade** [comment]
I think this also has something to do with different versions of aws-cdk-lib. My package is using 2.91, whereas cdk-monitoring-constructs is use 2.65. Cloudwatch might have introduced a compile time check between the two versions.

**Comment by Laxenade** [comment]
Easiest fix that I could think of is just strip out account and region somewhere in https://github.com/cdklabs/cdk-monitoring-constructs/blob/b07f3615de87e160081834d4816a1617565a1e76/lib/common/alarm/AlarmFactory.ts#L496 if the metric is a math expression. Though this might give the caller a false impression that MathExpression alarm can have custom `searchAccount` and `searchRegion`.

**Comment by echeung-amzn** [comment]
Yeah, #415 would be the cause of this and you should be right with the relation to global defaults being set.

We could potentially pass in the stack's info to `MetricFactory` and only use the global defaults for the `searchRegion` and `searchAccount` if they're actually different.

You'd still encounter the error if you try to alarm on those given you can't do search expressions cross-region/region anyway.

---

[Where the error's thrown, for reference](https://github.com/aws/aws-cdk/blame/c695b6004219426cf0e67cbb92d916a394ddd594/packages/aws-cdk-lib/aws-cloudwatch/lib/alarm.ts#L385-L393)

**Comment by edisongustavo** [comment]
Does this mean that I can't deploy a stack with alarms containing a `MathExpression` where the resources being monitored are in another account?

I started having this problem when monitoring my RDS cluster (`monitorRdsCluster()`). I specify the `account` at `metricDefaults.account` for this to work.
