### ISSUE TITLE
[ec2] add filter of instance IDs

### ISSUE THREAD

**Issue by ayush987goyal** [cdklabs/cdk-monitoring-constructs#43]
As a customer:

> I would just prefer a property under .monitorEC2instances that would allow me to specify instance ID's or something along those lines. I didn't deploy the instances via an ASG, so it seems like an all or nothing approach using this construct.

**Comment by voho** [comment]
If ASG is undefined, all instances are monitored and the metrics are created as a metric search expression. I think we need a different approach for a list of IDs - we do not want to use search expression, but iterate throught the ID, and create one metric for each instance separately, then combine them in a widget.
