### ISSUE TITLE
monitorApiGatewayV2HttpApi apiResource docs

### ISSUE THREAD

**Issue by uttrasey** [cdklabs/cdk-monitoring-constructs#440]
### Feature scope

apiResource docs

### Describe your suggested feature

Hello 👋 

When adding monitoring to an api gateway what can we put in `apiResource`?

```ts
      .monitorApiGatewayV2HttpApi({
        api: httpApi,
        apiResource: 'whatgoeshere',
      })
```

I tried using the path `/v1/service/{proxy}` but can't get it working. Some docs here would be great. Happy to add a PR once I understand it.

**Comment by echeung-amzn** [comment]
It should indeed be what can also referred to as a path: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-settings-method-request.html#setup-method-resources

If you're using a proxy resource, it might actually be `{proxy+}` rather than `{proxy}`.
