### ISSUE TITLE
[dynamo] addSystemErrorCountAlarm broken on CDK 1.135.0+

### ISSUE THREAD

**Issue by voho** [cdklabs/cdk-monitoring-constructs#48]
[This](https://github.com/aws/aws-cdk/pull/17738) change in 1.135.0 added some missing operations in the DynamoDB enum, which makes `metricSystemErrorsCount` exceed the limit of 10 alarms in metric math.

**Comment by echeung-amzn** [comment]
Would it potentially make sense to create the metrics in chunks of 10, then have an alarm based on a composite alarm of alarms for those chunked metrics?
