### ISSUE TITLE
Add fail-open metrics to Network Load Balancer monitoring

### ISSUE THREAD

**Issue by miloszwatroba** [cdklabs/cdk-monitoring-constructs#532]
### Feature scope

AWS/NetworkELB

### Describe your suggested feature

Hi,

I would like to propose adding a widget for fail-open monitoring in AWS Network Load Balancer monitoring. This will give a better visibility into whether the fail-open mechanism was triggered or not whenever all targets are unhealthy.

Documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html

Metric name: `UnhealthyRoutingFlowCount`
Available dimensions: 
* `LoadBalancer`
* `AvailabilityZone, LoadBalancer`

Is this something that we would like to integrate to the NLB monitoring constructs? If so, happy to contribute.

**Comment by echeung-amzn** [comment]
Yeah, that sounds useful to have in this library.
