### ISSUE TITLE
Lambda Support as CloudWatch Alarm Action

### ISSUE THREAD

**Issue by rememberYou** [cdklabs/cdk-monitoring-constructs#560]
### Feature scope

CloudWatch

### Describe your suggested feature

Since the end of December 2023, AWS now supports the triggering of a Lambda function as a CloudWatch Alarm action target (cf. https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-alarms-lambda-change-action/). This is useful, for example, when you want to modify the email body before sending it to another SNS topic where a list of email addresses is subscribed.

Currently, `cdk-monitoring-constructs` only supports SNS topics like CloudWatch Alarms action. Would it be possible to implement Lambda as an Alarm action as well?

**Comment by echeung-amzn** [comment]
Seems reasonable to add, but we'd need to bump up to >= v2.119.0 first (we're currently at >= v2.112.0).

https://github.com/aws/aws-cdk/commit/b9f49234d2c317d1c7dc143994d3e3b3b7bc430a

In the meantime if you're already using a newer version of `aws-cdk-lib`, you can implement something like [how SNS is handled](https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/common/alarm/action/SnsAlarmActionStrategy.ts), but using `LambdaAction`.
