### ISSUE TITLE
Type incompatibility between `MetricsFactory.createMetricSearch` and `monitorCustom`

### ISSUE THREAD

**Issue by adworacz** [cdklabs/cdk-monitoring-constructs#583]
### Version

8.3.1

### Steps and/or minimal code example to reproduce

Create a metric using a metrics factory `.createMetricSearch`, and then attempt to pass it to a monitoring facade using `monitorCustom`.

Essentially, the first two steps of https://github.com/cdklabs/cdk-monitoring-constructs?tab=readme-ov-file#custom-metrics, except that the documentation in the README is currently wrong. For example, there's no mention of the `metricGroups` property.

### Expected behavior

No Typescript errors

### Actual behavior

Typescript errors, specifically: `Type 'IMetric' is not assignable to type 'CustomMetric'`.

Screenshot:
![2024-10-22_15:30:21_maim](https://github.com/user-attachments/assets/f2b24ce3-e8f1-4841-856e-4ec94927a8c8)

**Comment by echeung-amzn** [comment]
> For example, there's no mention of the `metricGroups` property.

Yeah that's definitely wrong and needs to be updated.

> Typescript errors, specifically: `Type 'IMetric' is not assignable to type 'CustomMetric'`.

`CustomMetric` is:

https://github.com/cdklabs/cdk-monitoring-constructs/blob/3c5ec1bad7e721e13f99ac8da7750065e0eec81a/lib/monitoring/custom/CustomMonitoring.ts#L155-L159

And `MetricWithAlarmSupport` is:

https://github.com/cdklabs/cdk-monitoring-constructs/blob/main/lib/common/metric/MetricWithAlarmSupport.ts#L8

And while `Metric` implements `IMetric`:

https://github.com/aws/aws-cdk/blob/v2.163.1/packages/aws-cdk-lib/aws-cloudwatch/lib/metric.ts#L248

That doesn't mean an `IMetric` satisfies `Metric`.

Maybe we can make `createMetricSearch` return something more specific.

**Comment by adworacz** [comment]
Yeah, the other functions seem to use a variation of the type that they actually return, which in the case of this search function is `MathExpression`: 

https://github.com/cdklabs/cdk-monitoring-constructs/blob/3c5ec1bad7e721e13f99ac8da7750065e0eec81a/lib/common/metric/MetricFactory.ts#L167
