### ISSUE TITLE
[api-gateway] Allow selective metrics on latency graphs

### ISSUE THREAD

**Issue by echeung-amzn** [cdklabs/cdk-monitoring-constructs#65]
Currently, if we use .monitorAPIGateway(), it plots P50, P90, and P99 for latency by default. Such graphs are not required for every use case. A functionality can be added to allow the user to select the metrics that they needs plotted on the graph.

This should apply for both APIG v1 and v2, any may apply to other monitoring scopes as well.

**Comment by voho** [comment]
We can add the following to props:

```ts
    /**
     * You can specify what latency types you want to be rendered in the dashboards.
     * Note: any latency type with an alarm will be also added automatically.
     * If the list is undefined, default values will be shown.
     * If the list is empty, only the latency types with an alarm will be shown (if any).
     * @default avg, p50, p90, p99 (@see DefaultLatencyTypesShown)
     */
    readonly latencyTypesToRender?: LatencyType[];
```

**Comment by voho** [comment]
https://github.com/cdklabs/cdk-monitoring-constructs/pull/81
