### ISSUE TITLE
[synthetics] Support for CloudWatch Synthetics

### ISSUE THREAD

**Issue by echeung-amzn** [cdklabs/cdk-monitoring-constructs#73]
### Feature scope

CloudWatchSynthetics

### Describe your suggested feature

General support for metrics and alarms for CloudWatch Synthetics.

Metrics: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_metrics.html

**Comment by voho** [comment]
Started working on it.
